spring.profiles.active=mysql,spring-data-jpa
server.port=8000
server.context-path=/petclinic/
spring.messages.basename=messages/messages
logging.level.org.springframework=INFO
security.ignored=/**
basic.authentication.enabled=false
server.address=0.0.0.0