server {
    server_tokens off;
    set $es01 es01:9200;
    resolver 127.0.0.11;
    server_name es01.petclinic.lab;

    listen 443 ssl;
    include /etc/nginx/conf.d/ssl.conf;

    location / {
        proxy_http_version 1.1;
        proxy_pass https://$es01;

        proxy_set_header Accept-Encoding "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }
}
