server.host: "0.0.0.0"

telemetry.enabled: false

monitoring.ui.container.elasticsearch.enabled: false
monitoring.ui.container.logstash.enabled: false

server.publicBaseUrl: https://kibana.petclinic.lab
